### ISSUE TITLE
Compile failure on Windows

### ISSUE THREAD

**Issue by ataffeqeexo** [apple/swift-nio-transport-services#106]
### Expected behavior
The project properly compiles on Windows

### Actual behavior
`error: missing LinuxMain.swift file in the Tests directory` appears in the console

### Steps to reproduce

1. Attempt to compile a Vapor project on Windows Swift (using one of the latest development builds from https://github.com/compnerd/swift-build)
2. Note failure

### If possible, minimal yet complete reproducer code (or URL to code)

_[anything to help us reproducing the issue]_

### SwiftNIO version/commit hash

1.9.0

### Swift & OS version (output of `swift --version && uname -a`)
```
C:\SourceCache\redacted\desktop_client\shared\redacted>swift --version
compnerd.org Swift version 5.3-dev (LLVM 145d2f6acb3fff0, Swift 62a6a460594fb07)
Target: x86_64-unknown-windows-msvc
```

**Comment by Lukasa** [comment]
`LinuxMain.swift` is [right here](https://github.com/apple/swift-nio-transport-services/blob/main/Tests/LinuxMain.swift). Sounds like a Swift on Windows 5.3 bug.

**Comment by Lukasa** [comment]
Hmm, seems like SwiftPM on Windows is behaving differently. Normally that file will print a helpful error, but it seems that SwiftPM on Windows has started looking _inside_ that file to see if it's ok. I don't love that.

**Comment by ataffeqeexo** [comment]
To be honest I'm not entirely aware of the internal mechanisms of this, @compnerd, thoughts?

**Comment by compnerd** [comment]
@Lukasa - I don't see any special code paths in SPM to do that - so there is likely a latent SPM issue there.  But, yes `--enable-test-discovery` is going to be needed.
