### ISSUE TITLE
Can't build for release on iOS 15

### ISSUE THREAD

**Issue by hishnash** [apple/swift-nio-transport-services#124]
### Expected behavior
Should be able to build release build for iOS 15

### Actual behavior
Xcode has a build error

<img width="445" alt="image" src="https://user-images.githubusercontent.com/838127/129295595-2170d559-cdca-47e1-944b-c45254616914.png">

Looks like the system Network lib is missing an  `@available(macOS 12.0, iOS 15.0, watchOS 8.0, tvOS 15.0, *)` in the `Network` framework however im not sure. Looking at the exposed swift interface this extension should be wrapped in the @ available but maybe a change tho NIOTS would also solve this? Or maybe this is just a compiler bug, normally an extortion that only contains methods with `@available` does not need its own `@available`. 

```
extension Network.NWConnection {
  @available(macOS 12.0, iOS 15.0, watchOS 8.0, tvOS 15.0, *)
  convenience public init?(message: Network.NWConnectionGroup.Message)
  @available(macOS 12.0, iOS 15.0, watchOS 8.0, tvOS 15.0, *)
  convenience public init?(from: Network.NWConnectionGroup, to: Network.NWEndpoint? = nil, using: Network.NWProtocolOptions? = nil)
}
```

### Steps to reproduce

Add a a swift package to an Xcode project import/use it. And build a release build for iOS 15.

### SwiftNIO version/commit hash

<img width="262" alt="image" src="https://user-images.githubusercontent.com/838127/129295808-6df8fa5b-e6e4-47cb-bbb4-90a243315257.png">

### Swift & OS version (output of `swift --version && uname -a`)
```
swift-driver version: 1.26.7 Apple Swift version 5.5 (swiftlang-1300.0.27.6 clang-1300.0.27.2)
Target: x86_64-apple-macosx12.0
Darwin Matthauss-MacBook-Pro-2.local 21.0.0 Darwin Kernel Version 21.0.0: Mon Aug  2 00:18:11 PDT 2021; root:xnu-8019.30.9~9/RELEASE_X86_64 x86_64
```

**Comment by Lukasa** [comment]
Yup, this appears to be a bug in the SDK. There's nothing much we can do about that: can you please file a bug report using feedbackassistant.apple.com? Please feel free to comment with the feedback number here so we can keep track of it.
