### ISSUE TITLE
Failed to build module 'Network'; this SDK is not supported by the compiler 

### ISSUE THREAD

**Issue by saroar** [apple/swift-nio-transport-services#129]
### Expected behavior
I am trying to build for release 

### Actual behavior
_[what actually happened]_

### Steps to reproduce

1. ...
2. ...

### If possible, minimal yet complete reproducer code (or URL to code)

_[anything to help us reproducing the issue]_

### SwiftNIO version/commit hash
2.32.2
_[the SwiftNIO tag/commit hash]_

### Swift & OS version (output of `swift --version && uname -a`)
swift-driver version: 1.26.5 Apple Swift version 5.5 (swiftlang-1300.0.24.13 clang-1300.0.25.10)
Target: x86_64-apple-macosx11.0
Darwin Saroars-MacBook-Pro.local 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64

<img width="1440" alt="Screenshot 2021-09-12 at 22 15 49" src="https://user-images.githubusercontent.com/8770772/132999983-be289438-777e-436f-b472-4f369e9cb7e9.png">

Xcode 13 beta 5

**Comment by Lukasa** [comment]
I’m afraid this is an Xcode issue: you’ll need to file a feedback report using Feedback Assistant.

**Comment by saroar** [comment]
thanks for quick reply let me try to then use fastlane for deploy
