### ISSUE TITLE
Example for Bounjour service announcement would be useful

### ISSUE THREAD

**Issue by vvuk** [apple/swift-nio-transport-services#131]
I've got a swift-nio app working, and I wanted to add mDNS-based service discovery.  Basically, advertise my service on the port I already have things listening on (or advertise it on a random port, doesn't really matter).  I had hoped it would be just a matter of switching to `NIOTSEventLoop`, `NIOTSListenerBootstrap` etc., and then setting up a `bootstrap.bind(endpoint: .service(...))`, but that doesn't seem sufficient (I don't see the service getting advertised).

It would be really handy to have an example for this use case, since it's probably fairly common.

**Comment by tomerd** [comment]
swift-nio itself does not del with service discovery, but we also have https://github.com/apple/swift-service-discovery which provides the basic building blocks to build upon for such use cases

**Comment by vvuk** [comment]
Yeah, this is less about the discovery, and more about being able to receive a connection via a service broadcast.

It turns out it _was_ actually as easy as I described above, I just typo'd the service name in my Info.plist declaration! :/

**Comment by Lukasa** [comment]
Great, seems like this all got addressed.
