### ISSUE TITLE
URGENT : NIOTransportServices /  NIOTSConnectionBootstrap is only available in macOS 10.14 or newer

### ISSUE THREAD

**Issue by felswa** [apple/swift-nio-transport-services#159]
Hi. I have pulled updated my SPM in the past 30min and am getting this error which means I cannot build my entire project

#if swift(>=5.6)
@available(*, unavailable)
extension NIOTSConnectionBootstrap: Sendable {}
#endif

in NIOTSConnectionBootstrap.swift

These is my current Package. I am set to .v12 but it is possible that one of the packages is not. If you can please fix this issue. Thanks. 

/////

import PackageDescription

let package = Package(
    name: "DM123",
    platforms: [
         .macOS(.v12)
    ],
    dependencies: [
        // 💧 A server-side Swift web framework.
        .package(url: "https://github.com/vapor/vapor.git", from: "4.0.0"),
        .package(url: "https://github.com/vapor/fluent.git", from: "4.0.0"),
        .package(url: "https://github.com/vapor/fluent-mysql-driver.git", from: "4.0.0"),
        .package(url:"https://github.com/vapor/queues.git",from: "1.3.2"),
        .package(name: "QueuesFluentDriver", url: "https://github.com/m-barthelemy/vapor-queues-fluent-driver.git", from: "2.0.0"),

### Expected behavior
_[what you expected to happen]_

### Actual behavior
_[what actually happened]_

### Steps to reproduce

1. ...
2. ...

### If possible, minimal yet complete reproducer code (or URL to code)

_[anything to help us reproducing the issue]_

### SwiftNIO version/commit hash

_[the SwiftNIO tag/commit hash]_

**Comment by glbrntt** [comment]
What's the error you're seeing?

**Comment by felswa** [comment]
Hi. The project cannot build. On that line of code it says "NIOTSConnectionBootsrap is only available in macOS 10.14 or newer". Thanks.

**Comment by felswa** [comment]
#if swift(>=5.6)
@available(*, unavailable)
extension NIOTSConnectionBootstrap: Sendable {}
#endif

in NIOTSConnectionBootstrap.swift

**Comment by Skoti** [comment]
I believe it's because: `extension NIOTSConnectionBootstrap` is not included inside the missing else clause in:
```swift
#if swift(>=5.6)
@available(*, unavailable)
extension NIOTSConnectionBootstrap: Sendable {}
#endif
```
thus for swift 5.6 it tries to extend unavailable type.

I think it needs to be fixed for all such types that where marked `unavailable` [between 1.13.1 and 1.14.0](https://github.com/apple/swift-nio-transport-services/compare/1.13.1...1.14.0)

**Comment by felswa** [comment]
Also,  you have the following Package dependencies:

vapor -> async-http-client -> swift-nio-transport-services

In async-http-client Package & swift-nio-transport-services there does not seem to be a minimum platform version specified.

**Comment by felswa** [comment]
Thank you. Is it possible to do a new release so that we can pick up via SPM?

**Comment by glbrntt** [comment]
https://github.com/apple/swift-nio-transport-services/releases/tag/1.14.1

**Comment by Skoti** [comment]
Thanks for a quick fix! 🚀

**Comment by felswa** [comment]
Thanks very much!!
