### ISSUE TITLE
compilation on Linux

### ISSUE THREAD

**Issue by tanner0101** [apple/swift-nio-transport-services#21]
Currently SPM has no way of declaring dependency on a package per platform. This makes it impossible to dynamically depend on `NIOTS` only when on macOS / iOS (forbidding breaking cross-compilation with `#if` in `Package.swift`). 

SPM _should_ get the ability to declare dynamic dependencies, but until then it could be nice if we had a workaround solution.

I suggest making `NIOTS` compilable on Linux by wrapping all of the source code in `#if canImport(Network)`. By doing this, packages that want to dynamically rely on NIOTS can safely add it as a dependency to their project, and only attempt to use it within `#if canImport(Network)`

**Comment by weissi** [comment]
@Lukasa should we do this for `1.0.0`?

**Comment by Lukasa** [comment]
Sure.

**Comment by weissi** [comment]
Awesome, I’ll try to squeeze this in today :)
