### ISSUE TITLE
NIOTSListenerBootstrap incompatible with NIOExtras.ServerQuiescingHelper

### ISSUE THREAD

**Issue by ldewailly** [apple/swift-nio-transport-services#44]
### Expected behavior
I would like to use `NIOExtras.ServerQuiescingHelper` with `NIOTS` so I can better handle server quiescing. It works as intended with `NIO.ServerBootstrap` but not with `NIOTSListenerBootstrap `

### Actual behavior
The process crashes when processing a request:

```
Fatal error: tried to decode as type Channel but found NWConnection with contents other([C1 127.0.0.1:50360 tcp, interface: lo0, local: 127.0.0.1:50358, legacy-socket, server, path satisfied (Path is satisfied), interface: lo0, scoped]): file /Users/<truncated>/.build/checkouts/swift-nio.git--1696851023008440387/Sources/NIO/NIOAny.swift, line 200
```

### Steps to reproduce

The following code snippet illustrates how to reproduce the crash

1. Create a `NIOTS` HTTP server and start it
2. Invoke it (e.g. with `curl`)

### If possible, minimal yet complete reproducer code (or URL to code)

```swift
import NIO
import NIOTransportServices

let group = NIOTSEventLoopGroup()
let quiesce = ServerQuiescingHelper(group: group)
let serverChannel = NIOTSListenerBootstrap(group: group)
  .serverChannelInitializer { channel in
    // add the collection handler so all accepted child channels get collected
    channel.pipeline.add(handler: quiesce.makeServerChannelHandler(channel: channel))
  }
  .bind([...])
  .wait()

// make a request to the server, this will trigger the above crash.
```

### SwiftNIO version/commit hash

`NIO`: 2.1.1
`NIOTS`: 1.0.2
`NIOExtras`: 1.1.0

### Swift & OS version (output of `swift --version && uname -a`)

`Apple Swift version 5.0.1`

**Comment by Lukasa** [comment]
So the NIOTransportServices `AcceptHandler` doesn't operate on channels but on `NWConnection`s. That's probably not ideal: we should probably fire the channel down the pipeline instead of the connection. I can't recall if there is any reason I did it this way.

**Comment by Lukasa** [comment]
@weissi Do you believe there is a semver risk here? My inclination is to say no, because no-one is writing handlers in the server channel anyway, but feel free to make the case the other way.

**Comment by weissi** [comment]
@Lukasa agreed and also I'd say that was a plain bug.

**Comment by Lukasa** [comment]
Cool ok, thanks. Should be easily fixed.
