### ISSUE TITLE
should have api docs

### ISSUE THREAD

**Issue by weissi** [apple/swift-nio-transport-services#5]
we should have API docs for this at http://docs.swiftnio.io

**Comment by Palleas** [comment]
@weissi do you mean jazzy-generated docs?

**Comment by weissi** [comment]
@Palleas yes, they should be posted alongside those guys: https://apple.github.io/swift-nio/docs/current/NIO/index.html

**Comment by Lukasa** [comment]
Closing to unify this around #14.
