### ISSUE TITLE
Is CocoaPods still supported?

### ISSUE THREAD

**Issue by bofeizhu** [apple/swift-nio-transport-services#64]
I found that the CocoaPods specs are out-dated for all `Swift-NIO` projects. Are we dropping support for CocoaPods?

**Comment by weissi** [comment]
@bofeizhu sorry about that. Xcode's package support is the preferred way to use SwiftNIO on Apple platforms but CocoaPods is still supported. I updated them all, please let us know if there are any issues.

**Comment by bofeizhu** [comment]
@weissi Could we create a GitHub Action that automatically push to CocoaPods for each release?
