### ISSUE TITLE
Errors are not being reported while connection is in activating state

### ISSUE THREAD

**Issue by adam-fowler** [apple/swift-nio-transport-services#75]
### Expected behavior
Errors to be reported back

### Actual behavior
If an error occurs `NIOTSConnectionChannel.stateUpdateHandler` is called with state .waiting(error). At this point if the state is activating the code chooses to do nothing. If this error is a DNS error the only way for the connection to fail after that point is for it to timeout. 

### Steps to reproduce

1. Using niots branch of https://github.com/adam-fowler/async-http-client/
2. Connect to web address that doesn't exist.
3. A DNS error is sent back from Network.framework but it is ignored

### If possible, minimal yet complete reproducer code (or URL to code)
This is taken from async-http-client tests. I just changed "localhost" to "localhost2"
```
    func testGet() throws {
        let httpBin = HTTPBin()
        let httpClient = HTTPClient(eventLoopGroupProvider: .shared(self.clientGroup))
        defer {
            XCTAssertNoThrow(try httpClient.syncShutdown(requiresCleanClose: true))
            XCTAssertNoThrow(try httpBin.shutdown())
        }

        let response = try httpClient.get(url: "http://localhost2:\(httpBin.port)/get").wait()
        XCTAssertEqual(.ok, response.status)
    }
```

### SwiftNIO version/commit hash
swift-nio-transport-services master branch
swift-nio 2.15.0

### Swift & OS version (output of `swift --version && uname -a`)
Target: x86_64-apple-darwin19.3.0
Darwin Adams-MBP 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64

**Comment by Lukasa** [comment]
This is a deliberate behaviour and can be opted out of. When Network.framework transitions a socket to `.waiting` it is instructing the user-code that a change in network condition may lead to a new connection attempt: for example, moving Wifi network or disabling airplane mode. For this reason, NIO chooses to wait for the connection timeout.

Code that does not wish to wait may set the `WaitForActivity` channel option to `false` (see #15).
