### ISSUE TITLE
NIOTSListener.bindPromise is disappearing

### ISSUE THREAD

**Issue by AlanQuatermain** [apple/swift-nio-transport-services#8]
Looking at: https://github.com/apple/swift-nio-transport-services/blob/fb47fc1614ab391da593554cbf6718da90528f30/Sources/NIOTransportServices/NIOTSListenerChannel.swift#L282.

If we fail to create the `NWListener`, we call `self.close0()` with the error. Inside `close0` we immediately see that `self.nwListener` is `nil`, and exit doing nothing else. In this situation, `self.bindPromise`, aka the `promise` parameter to `beginActivating0()` is just left dangling.

I would guess that the catch block should look like this:

```swift
self.close0(error: error, mode: .all, promise: nil)
self.bindPromise?.fail(error: error)
self.bindPromise = nil
return
```

However, I'm not certain that's necessarily the right way to go about it. Any comments? I'm happy to submit the fix if my supposition above is actually correct.

**Comment by AlanQuatermain** [comment]
Alternatively, we could instead change `close0()` to look like this:

```swift
public func doClose0(error: Error) {
    // Step 1: tell the networking stack (if created) that we're done.
    if let listener = self.nwListener {
        listener.cancel()
    }
    
    // Step 2: fail any pending bind promise.
    if let pendingBind = self.bindPromise {
        self.bindPromise = nil
        pendingBind.fail(error: error)
    }
}
```

**Comment by Lukasa** [comment]
I think the second proposed fix is the way to go here, it’s much more likely to be correct.

**Comment by normanmaurer** [comment]
+1
