### ISSUE TITLE
watchOS build failure

### ISSUE THREAD

**Issue by Bricon66** [apple/swift-nio-transport-services#97]
I'm new to swift and iOS development, but from what I've read swift-nio transport services support watchOS since 1.1.0?  I'm having trouble building a library that references grpc-swift, and ultimately transport services, with the below build error.  

A clone of the repo and attempt to build on Apple Watch Series 5 yields the same result.  Just wondering if anyone can shed some light on if this might be an issue or if I have something setup wrong?

### Expected behavior
Build success for Apple Watch Series 5 device

### Actual behavior
![Screen Shot 2020-06-18 at 8 19 54 PM](https://user-images.githubusercontent.com/3331809/85083883-19dd3580-b1a1-11ea-8143-8190ec2da7bf.png)

### Steps to reproduce

1. Build the package for Apple Watch Series 5

### SwiftNIO version/commit hash

2.18.0

### Swift & OS version (output of `swift --version && uname -a`)

Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)
Target: x86_64-apple-darwin19.5.0
Darwin PA90C02Z50WYLVDTC02Z50WYLVDT 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64

**Comment by Lukasa** [comment]
Good catch! #98 will fix this.

**Comment by Bricon66** [comment]
Awesome! Thanks @Lukasa
